import type { Metadata } from "next";
import { Geist, Geist_Mono, Parisienne, Water_Brush } from "next/font/google";
import "./globals.css";
import Topbar from "./shared/topbar";
import TopbarMobile from "./shared/mobileSideBar";
import Footer from "./shared/footer";

const parisienne = Parisienne({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-parisienne",
});

const water = Water_Brush({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-parisienne",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pilgrims Evangelical Church",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${parisienne.variable} ${water.variable} h-full antialiased bg-black`}
    >
      <body className="min-h-full flex flex-col">
        {" "}
        {/* <Topbar /> */}
        <TopbarMobile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
